name: SilverNP
channels:
  - conda-forge
dependencies:
  - numpy=1.21.5
  - pip=23.1.2
  - python=3.9.16
  - scipy=1.10.1
  - matplotlib=3.4.3
  - pip:
    - ipykernel==6.15.0
    - ipython==8.4.0
    - jupyter==1.0.0
    - notebook==6.4.12
    - numpyencoder==0.3.0
    - openpyxl==3.0.10
    - pandas==1.3.5
    - scikit-learn==1.2.2
    - shap==0.41.0
